# Generated by Django 5.1.4 on 2024-12-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='can_create',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_read',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_write',
        ),
    ]
